blank_issues_enabled: false
contact_links:
  - name: Community Discussions
    url: https://github.com/Yannis-A-D/encrypted_sqlite_system/discussions
    about: Ask questions, share ideas, and connect with other developers.
